name: i18n Updater

on:
    push:
        branches:
            - main
        paths:
            - "i18n/_officialTwitterI18n.json"
            - "i18n/_officialTwitterI18nConfig.json"
    workflow_dispatch:

jobs:
    eslint:
        name: Update
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Update
              run: |
                  yarn add node-fetch

                  node ./updateI18n.mjs
                  git config user.name  "i18n Updater"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "generated"
                  git push
