name: Lint

on:
    push:
        branches: ["main"]
    pull_request:
        # The branches below must be a subset of the branches above
        branches: ["main"]
    workflow_dispatch:

jobs:
    lint:
        name: Run ESLint & Prettier scanning
        runs-on: ubuntu-latest
        #permissions:
        #    contents: read
        #    security-events: write
        #    actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install ESLint & Prettier
              run: |
                  yarn add eslint
                  yarn add prettier
                  yarn add eslint-config-prettier
                  yarn add @typescript-eslint/eslint-plugin
                  yarn add @typescript-eslint/parser
            #      yarn add @microsoft/eslint-formatter-sarif
            #
            #- name: Generate SARIF file
            #  run: |
            #      yarn lint:eslint -f @microsoft/eslint-formatter-sarif -o eslint-results.sarif
            #  continue-on-error: true
            #
            #- name: Upload SARIF file
            #  uses: github/codeql-action/upload-sarif@v2
            #  with:
            #      sarif_file: eslint-results.sarif
            #      wait-for-processing: true

            - name: Run ESLint & Prettier
              run: |
                  yarn lint
              continue-on-error: false
